#!/usr/bin/env bash

# config for DDPG
# critic_lr=1e-3,
# actor_lr=1e-4,
# gamma=0.99,
# batch_size=100,
# ev_n_steps=1000,
# num_steps = 1e6

python ddpg_adnan.py -s 10 -i 6

python ddpg_adnan.py -s 69 -i 7

python ddpg_adnan.py -s 7 -i 8